package info.fandroid.radioapp

const val BASE_URL = "https://at1.api.radio-browser.info/json/"

const val PLAYBACK_NOTIFICATION_CHANNEL_ID = "BRRBJ7P75YZL7U64SMH6GX9UA7ZBEI"

const val PLAYBACK_NOTIFICATION_ID = 328631640732565

const val MEDIA_ROOT_ID = "MV412EN29X1QW3ZVWW49"

const val START_MEDIA_PLAYBACK_ACTION = "START_MEDIA_PLAYBACK_ACTION"

const val REFRESH_MEDIA_BROWSER_CHILDREN = "REFRESH_MEDIA_BROWSER_CHILDREN"

const val PLAYBACK_POSITION_UPDATE_INTERVAL = 1000L

const val ACTION_RADIO_NOTIFICATION_CLICK = "ACTION_RADIO_NOTIFICATION_CLICK"

const val API_REQUEST_ORDER = "votes"
